name: pokedex
description: An study project using pokedex example.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx:
  flutter_mobx:
  cached_network_image: ^2.0.0
  provider: ^4.0.1
  md2_tab_indicator: ^1.0.2
  flutter_staggered_animations: ^0.1.2
  sliding_sheet: ^0.2.4
  flutter_icons: ^1.0.0+1
  intl: ^0.16.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeballBlack.png
    - assets/images/pokeballColor.png

fonts:
  - family: Google
    fonts:
      - asset: assets/fonts/ProductSansRegular.ttf
      - asset: assets/fonts/ProductSansBold.ttf
        weight: 700
